import {createTheming} from '@callstack/react-theme-provider';

export const theme = {
  lightColor: {
    white: '#FFFFFF',
    black: '#000000',
    background: '#FBF8F0',
    lightBlack: '#181615',
    orange: '#EC832D',
    darkOrange: '#FF8C09',
    gray: '#F4F1E9',
    transparent: 'rgba(0, 0, 0, 0.4)',
    red: '#EA5358',
    darkRed: '#F74F43',
    darkGray: '#989691',
    green: '#63BC28',
    lightGreen: '#67C175',
    cgreen: '#4CDB70',
    error: '#FF6640',
    blurColor: '#EAE6DB',
    cgray: '#455154',
    desGray: '#959595',
    brown: '#2A2726',
    darkBrown: '#33302F',
    yellow: '#FED730',
    darkYellow: '#F8C50F',
    lightYellow: '#DFAE01',
    rgbaColor: 'rgba(0,0,0,0.5)',
    lightBorder: 'rgba(0, 0, 0, 0.06)',
    cream: '#FFFAE5',
    darkCream: '#F7EEC9',
    cyan: '#E7F4EC',
    lightSkin: '#F7F0DE',
    blue: '#3E5155',
    shade: '#2E2D2C',
    tutorialBG: 'rgba(50, 63, 75, 0.1)',
    linkBG: '#F5EFDA',
    dateColor: '#333333',
    whiteRgba: 'rgba(255, 255, 255, 0.8)',
    greenish: '#0CB38C',
    parrot: '#96C05C',
    lightWhite: '#ECECEC',
    indicatorClr: '#D4D1CB',
  },
  darkColor: {},
  fontWeight: {
    normal: '400',
    medium: '500',
    semiBold: '600',
    bold: '700',
    extraBold: '900',
  },
  fontFamily: {
    SFProDisplayRegular: 'SFProDisplay-Regular',
    SFProDisplayMedium: 'SFProDisplay-Medium',
    SFProDisplayBold: 'SFProDisplay-Bold',
    // PoppinsBold: 'Poppins-Bold',
    // PoppinsMedium: 'Poppins-Medium',
    // PoppinsRegular: 'Poppins-Regular',
    // MontserratBold: 'Montserrat-Bold',
    // MontserratMedium: 'Montserrat-Medium',
    // SahityaBold: 'Sahitya-Bold',
  },
  animation: {
    scale: 1.0,
  },
};

const {ThemeProvider, withTheme, useTheme} = createTheming(theme);

export {ThemeProvider, withTheme, useTheme};
